### ISSUE TITLE
Hard time using inheritance

### ISSUE THREAD

**Issue by tomsiwik** [jsonapi-suite/jsorm#123]
Hi there. This is not an issue per se but a problem/riddle I'm trying to solve that I've been currently unable to get my head around. Here goes:

- I wrote a simple scaffolding script that creates my models based on the database structure. One such model looks like this:

```javascript
import { Attr, HasMany, Model } from "jsorm";

import { TextColour, ApplicationRecord } from "../";

@Model()
export class ColourBase extends ApplicationRecord {
  static jsonapiType: string = "colours";

  @Attr() name: string;
  @Attr() standard: string;

  @HasMany() textColours: TextColour[];
}
```

- These model classes I would rather not touch but extend with a second class similar to this:

```javascript
import { Model } from "jsorm";

import { ColourBase } from ".";

@Model()
export class Colour extends ColourBase {
  get stringify() {
    return `${this.name}${this.standard ? ` (${this.standard})` : ""}`;
  }
}

// Doesn't seem to do anything
// ColourBase.inherited(Colour)
```

- When I request all my colours with `Colour.all()` only an array of `ColourBase` are returned. Meaning I can not use the `stringify` getter. I suspect this is intended behaviour. But here is the riddle/question:

_How can I return the last child-class as model rather than the immediate child of `ApplicationRecord`. Or... how can I solve my problem differently?_

I have tried with mixins but it rather conflicts with `@Model` decorators or `JSORMBase` not having properties set. Swapping inheritance of both classes has similar issues. Any ideas I can try?

I've found `extend`, `inherited` and `ExtendedModel`. 

Update:
- `inherited` does nothing
- `extend` model variant also serialises to Base Model rather than caller Model
- `ExtendedModel` not sure how to use this one
- `setAsBase` isn't doing what I was thinking

**Comment by richmolj** [comment]
Looks like you're doing some interesting work @tomsiwik!

I *think* I can help. The premise here is we get a response from the server with a jsonapi `type`. We then look through all models and take the first model that has that `type` associated.

It sounds like `ColourBase` isn't truly a model as much as an abstract superclass. If you removed the jsonapi type there (or changed it to 'color_bases' or w/e), and moved it to `Colour`, I think it would work.

**Comment by tomsiwik** [comment]
Can you direct me to that part of the code that checks the `jsonapiType` just so I know how it's handled? I will try your suggestion.

Edit: Oh my god! It works 🤩! Thank you so much. 

Maybe this can help others I'll write a quick solution here:

### 1st Step
```javascript
import { Attr, HasMany, Model } from "jsorm";

import { TextColour, ApplicationRecord } from "../";

@Model()
export class ColourBase extends ApplicationRecord {
  // Remove type otherwise it will be registered to this class
  // static jsonapiType: string = "colours";

  @Attr() name: string;
  @Attr() standard: string;

  @HasMany() textColours: TextColour[];
}
```

### 2nd Step
```javascript
import { Model } from "jsorm";

import { ColourBase } from ".";

@Model()
export class Colour extends ColourBase {
  // Add type here because we want this class registered as our 
  // target model extending our abstract class above
  static jsonapiType: string = "colours";

  get stringify() {
    return `${this.name}${this.standard ? ` (${this.standard})` : ""}`;
  }
}
```

**Comment by richmolj** [comment]
Nice! You can follow the code from here https://github.com/graphiti-api/spraypaint.js/blob/master/src/model.ts#L235-L240
