### ISSUE TITLE
Question: Set the authorization token on a different format

### ISSUE THREAD

**Issue by fmquaglia** [jsonapi-suite/jsorm#27]
Hello,

This library looks *almost* perfect for a React/Redux project in which I'm working.
The only caveat is that I need the authorization token in a different format.

Something like: ```Authorization: Bearer xxxxxxx```

I saw that the token format is hardcoded in a string template [here](https://github.com/jsonapi-suite/jsorm/blob/38310ba3b451a04042ca8916bee82ab577b0460b/src/model.ts#L85).
So I am wondering if there is a way to change its format.

**Comment by richmolj** [comment]
Hey @fmquaglia - right now you can override `fetchOptions`:

```
class ApplicationRecord extends Model {
  static fetchOptions() {
    let opts = super
    if (opts.headers.Authorization) {
      opts.headers.Authorization = `Bearer ${this.getJWT()}`
    }
  }
}
```

That said, I'd definitely merge a PR that extracted the auth header string into a separately-overrideable method.

Does that work for you?

**Comment by fmquaglia** [comment]
Hey @richmolj thanks for the prompt reply.

The idea of having a static method to override the default auth token sounds great.
I'm not a TS developer, unfortunately, to help you there.
If you are short of time just hint me to get started and I could follow your directives.

LMK

**Comment by richmolj** [comment]
I think just take [this line](https://github.com/jsonapi-suite/jsorm/blob/38310ba3b451a04042ca8916bee82ab577b0460b/src/model.ts#L85) and change it to:

```ts
options.headers.Authorization = this.generateAuthHeader(this.getJWT())
```

And add the corresponding method to the class:

```ts
static generateAuthHeader(jwt: string) : string {
  return `Token token="${jwt}"`;
}
```

After that we'd just need to add a test similar to [this one](https://github.com/jsonapi-suite/jsorm/blob/38310ba3b451a04042ca8916bee82ab577b0460b/test/integration/authorization-test.ts#L9-L28), but using a different class that overrides `generateAuthHeader`. Run `npm run test` to test.

If it gets wonky, I can take care of this, just not today. Thanks!

**Comment by fmquaglia** [comment]
I'm giving it a try. Thanks for the help. hopefully you´ll get a PR soon enough @richmolj

**Comment by fmquaglia** [comment]
@richmolj although I managed to implement ```generateAuthHeader``` as you explained to me I'm tuck with the testing.

Please take a look at [this commit in my fork](https://github.com/fmquaglia/jsorm/commit/d110d7fbd7dc947cbd098ba953150877cd8571ad#diff-fd7f45d729d2cb14add6ff80822c1b9b) when you have the chance.
what am I doing wrong?

**Comment by fmquaglia** [comment]
@richmolj you should close this.
