### ISSUE TITLE
use patch instead of put for updating an object

### ISSUE THREAD

**Issue by jannishuebl** [jsonapi-suite/jsorm#63]
Hi,

I am new to the json:api topic so please correct me, if I am wrong:

The json:api specification says, that we have to use PATCH for updating a resource. described here: http://jsonapi.org/format/#crud-updating

jsorm currently uses PUT for this purpose. My backend lib is following the json:api standard at the moment.

Thanks,

Jannis

**Comment by richmolj** [comment]
Yep, sounds like a bug. Will be getting to it in the next week or two unless you want to submit a PR :)
