### ISSUE TITLE
attributes that are kebab-case are not camelcased correctly

### ISSUE THREAD

**Issue by jannishuebl** [jsonapi-suite/jsorm#66]
Hi,

when a attribute is in kebab-case format, which seems to be very common when using json:api, the camel case method in string.ts is not catching the attribute name.

see:  https://github.com/jsonapi-suite/jsorm/blob/5b28e6d4d7f2b5b65771c4082bcab93677f7e9ab/src/util/string.ts#L6
 
I have not found if attribute naming-convention is somewhere defined for json:api.

I guess it should be a small fix, if you like I can take this issue over and create a pullrequest for it. 

Kind Regards,

Jannis

**Comment by richmolj** [comment]
Yes, we should absolutely support this. The APIs I've seen use underscored keys, but we should support kebab-case as well. Would love to see a PR, though I'd suggest making it to the `1.x-dev` branch which will be released shortly. Keep in mind we'll have to both read and write the correct keys. 

Related PRs for reference https://github.com/jsonapi-suite/jsorm/pull/24 https://github.com/jsonapi-suite/jsorm/pull/21

**Comment by jannishuebl** [comment]
@richmolj thanks for the advise about the writing of the correct format. do you see any other possibility, then to add is as a configuration parameter to the model? 

eg:

```
const Person = Model.extend({
  static {
    baseUrl: 'http://localhost:3000',
    jsonapiType: 'people',
    letterCase: 'kebab-case'
  },
```

letterCase could be default to 'snake_case' / 'underscored' and can be set to "kebab-case" so we do not break the current semantic. 

Another possibility could be to set the separator char. eg: "_" or "-", I would prefer the first solution, what do you think about this?
