### ISSUE TITLE
1.0.0 Beta breaks your examples for the Quickstart

### ISSUE THREAD

**Issue by happycollision** [jsonapi-suite/jsorm#67]
I'd do a PR for the quick start page at jsonapi-suite.org, but I can't find it.

Just need to change npm install step to require a compatible version of jsorm.

**Comment by richmolj** [comment]
Docs are now updated but let's keep this open for 1.0

**Comment by wadetandy** [comment]
Have added a deprecation warning to the `1.0.0-beta1` release recommending using `0.5.6` and have submitted a support ticket to NPM to either unpublish or mark as beta the package in question. Sorry for the confusion!

**Comment by richmolj** [comment]
This release is now properly tagged as beta
