### ISSUE TITLE
[1.0] export 'Config' was not found in 'jsorm'

### ISSUE THREAD

**Issue by swrobel** [jsonapi-suite/jsorm#68]
Using 1.0.0-beta1 in an ES6 file w/ Webpack 3, the following from the docs fails with `"export 'Config' was not found in 'jsorm'`:

```js
import { Config } from "jsorm"
Config.setup()
```

**Comment by richmolj** [comment]
Hey @swrobel - this is really an npm tagging issue, we haven't written documentation for the beta release of 1.0 yet. Please use 0.5.6 until we release 1.0 very shortly. /cc @wadetandy
