### ISSUE TITLE
[1.0] jsorm__.b.extend is not a function

### ISSUE THREAD

**Issue by swrobel** [jsonapi-suite/jsorm#69]
Using 1.0.0-beta1 in an ES6 file w/ Webpack 3, the following from the docs fails with `__WEBPACK_IMPORTED_MODULE_4_jsorm__.b.extend is not a function`:

```js
import { Config, Model, attr, hasMany, belongsTo } from 'jsorm';

const Person = Model.extend({
  static {
    baseUrl: 'http://localhost:3000',
    jsonapiType: 'people'
  },

  firstName: attr(),
  lastName: attr(),
  fullName() {
    return this.firstName + ' ' + this.lastName;
  }
});
```

**Comment by richmolj** [comment]
Hey @swrobel - this is really an npm tagging issue, we haven't written documentation for the beta release of 1.0 yet. Please use 0.5.6 until we release 1.0 very shortly. /cc @wadetandy

**Comment by wadetandy** [comment]
Have added a deprecation warning to the `1.0.0-beta1` release recommending using `0.5.6` and have submitted a support ticket to NPM to either unpublish or mark as beta the package in question. Sorry for the confusion!
